
export interface InternationalShipment{
    id: number|null|undefined,
  originCountry: string|null|undefined,
  originPort: string|null|undefined,
  refrigeratedTruck: boolean|null|undefined,
  type: string|null|undefined,
  shipmentMode: string|null|undefined,
  preAlertNumber: string|null|undefined,
  destinationCountry: string|null|undefined,
  destinationPort: string|null|undefined,
  carrier: string|null|undefined,
  departureDateAndTime: Date|null|undefined,
  etd: Date|null|undefined,
  eta: Date|null|undefined,
  atd: Date|null|undefined,
  flightNumber: number|null|undefined,
  numberOfShipments: number|null|undefined,
  arrivalDateAndTime: Date|null|undefined, 
  actualWeight: number|null|undefined,
  driverName: string|null|undefined,
  driverContact: string|null|undefined,
  referenceNumber: string|null|undefined,
  vehicleType: string|null|undefined,
  numberOfPallets: number|null|undefined,
  numberOfBags: number|null|undefined,
  vehicleNumber: string|null|undefined,
  tagNumber: number|null|undefined,
  sealNumber: number|null|undefined,
  attachments: string|null|undefined,
  status: string|null|undefined,
  remarks: string|null|undefined,
  routeNumber: string|null|undefined,
  ata: Date|null|undefined,
  totalShipments: number|null|undefined,
  overages: string|null|undefined,
  overageAWBs: string|null|undefined,
  received: string|null|undefined,
  shortages: string|null|undefined,
  shortageAWBs: string|null|undefined,
}

interface Time{
    date: number|null|undefined,
    hours:  number|null|undefined,
    minutes:  number|null|undefined,
    month:  number|null|undefined,
    seconds:  number|null|undefined,
    time:  number|null|undefined,
    year:  number|null|undefined
}